[project]
name = "alpaca-cli"
version = "0.3.0"
description = "A command-line interface for Alpaca API."
readme = "README.md"
authors = [
    { name = "hades", email = "nischalbhattaraipi@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alpaca-py>=0.43.2",
    "click>=8.3.1",
    "plotext>=5.3.2",
    "pytz>=2025.2",
    "rich>=14.2.0",
    "rich-click>=1.8.3",
    "textual>=0.52.1",
    "textual-plotext>=1.0.1",
]

[project.scripts]
alpaca-cli = "alpaca_cli.cli.main:cli"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
